# Generated by Django 5.0 on 2023-12-20 16:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qna", "0002_remove_answer_updated_at_alter_answer_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="생성 시간"
            ),
        ),
    ]
