# Generated by Django 5.0 on 2023-12-22 18:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qna", "0007_alter_answer_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="생성 시간"
            ),
        ),
    ]
