# Generated by Django 5.0 on 2023-12-24 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qna", "0008_alter_question_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="author",
            new_name="student_id",
        ),
    ]
