# Generated by Django 5.0 on 2023-12-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qna", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="answer",
            name="created_at",
            field=models.DateTimeField(verbose_name="생성 시간"),
        ),
        migrations.AlterField(
            model_name="question",
            name="created_at",
            field=models.DateTimeField(verbose_name="생성 시간"),
        ),
    ]
