# Generated by Django 5.0 on 2023-12-20 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qna", "0003_alter_answer_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="qna.question",
                verbose_name="질문",
            ),
        ),
    ]
