# Generated by Django 5.0 on 2023-12-22 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qna", "0006_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="qna.question",
                verbose_name="질문",
            ),
        ),
    ]
