# Generated by Django 5.0 on 2023-12-24 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qna", "0009_rename_author_question_student_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="student_id",
            new_name="author",
        ),
    ]
