# Generated by Django 5.0 on 2023-12-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qna", "0010_rename_student_id_question_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="modified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="modified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
